### ISSUE TITLE
Missing infromation.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Yuni-Site#1]
We are missing the following things:

- [x] Google Calendar embed URL for calendar page;
- [x] Recipient email for contact form;
- [x] Facebook page URL;
- [x] Login URL for students.

**Comment by talovdat** [comment]
Recipient email for contact form: provided via email.

Facebook page URL: 
https://www.facebook.com/%D7%94%D7%AA%D7%9B%D7%A0%D7%99%D7%AA-%D7%9C%D7%A0%D7%95%D7%A2%D7%A8-%D7%9E%D7%95%D7%9B%D7%A9%D7%A8-%D7%91%D7%9E%D7%AA%D7%9E%D7%98%D7%99%D7%A7%D7%94-132623920141109/?ref=ts&fref=ts&sw_fnr_id=1900490535&fnr_t=0

Login URL for student: 
https://app.tepez.co.il/#/f/56a89b709fb3c5d71f296707/run/
![image](https://user-images.githubusercontent.com/26923359/29002589-9dc7f326-7aae-11e7-850f-1dc0c1b43c16.png)


Assigned and changing assigned requests:
https://app.tepez.co.il/#/f/550feadef0db8db40697db02/run/
![image](https://user-images.githubusercontent.com/26923359/29002615-28df5738-7aaf-11e7-8caf-09e67dc382ef.png)

Payment
https://pay.yuni.co.il/Screens/MainPage.aspx?IsSecure=True
![image](https://user-images.githubusercontent.com/26923359/29002646-c9b00c70-7aaf-11e7-9cab-9fd1c0cf1fd1.png)

**Comment by talovdat** [comment]
@MeanEYE, Client gave me access to calendar(user and password) .
How do you want to do this?

**Comment by MeanEYE** [comment]
@talovdat do you know how to get iCal URL from a specific calendar?

**Comment by talovdat** [comment]
Not really

**Comment by MeanEYE** [comment]
In calendar settings there's this:
![image](https://user-images.githubusercontent.com/1911594/29275476-8624d744-810b-11e7-9f8c-355588fad166.png)
I need that code.

**Comment by talovdat** [comment]
Here it ok?

**Comment by MeanEYE** [comment]
Yes.

**Comment by talovdat** [comment]
iCal URL:
<iframe src="https://calendar.google.com/calendar/embed?src=yuniexcel%40gmail.com&ctz=Asia/Jerusalem" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
