### ISSUE TITLE
Searching the word 'courses'

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#103]
The search algorithm is working fine besides one important subject. 
I try searching 'courses' and it gave me a blank page.

![image](https://user-images.githubusercontent.com/26923359/38175619-31a9a932-35e8-11e8-8c1d-5c3174a97e72.png)

**Comment by MeanEYE** [comment]
Search algorithm is looking for content. This issue is valid only when word search for is inside of article but doesn't appear in results.

**Comment by talovdat** [comment]
Word is not showing in the articles.
