### ISSUE TITLE
Contact us page - message field

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#109]
http://yuni.co.il.82-223-16-124.eu1.way2cu.work/contact-us 

We need to add a message field where the user can fill free text.

**Comment by MeanEYE** [comment]
You don't need to specify the whole URL @talovdat . Just `/contact-us` is enough. There aren't more than one Yuni site.

**Comment by MeanEYE** [comment]
Why is this message field requested now? This is adding new stuff and I don't want to do that.
