### ISSUE TITLE
Location pop ups doesnt show full image - mobile

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#11]
On locations page, when clicking on one of the locations, the popup doesn't show fully window. 
http://yuni.co.il.82-223-16-124.eu1.way2cu.work/locations

![image](https://user-images.githubusercontent.com/26923359/30015060-c216c7a6-9157-11e7-86f9-b90f890272c5.png)

**Comment by MeanEYE** [comment]
It's a fucking popup. If they want to write articles, then we can make a separate page. Design showed short information, not essays.

**Comment by MeanEYE** [comment]
We need to resolve this one @talovdat. Either we make separate pages, or client shortens dialogs. One of the two.

**Comment by talovdat** [comment]
Client didn't say anything about that. 
If she does, I'll talk to her to just shortens the dialogs.
Am closing issue, and if necessary I'll reopen it.
