### ISSUE TITLE
Page layout 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#119]
http://yuni.co.il.82-223-16-124.eu1.way2cu.work/registration/sign-up/07exposurs_inf_2

In the URL above you can see that the page layout got messed up with the bullets text. 
![image](https://user-images.githubusercontent.com/26923359/39407593-08ccbdc0-4bd1-11e8-9bfc-80cd3ea7445c.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev check if this one is an issue caused by us or by entering content the wrong way.
