### ISSUE TITLE
Inner pages looks bad - mobile

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#12]
For example, http://yuni.co.il.82-223-16-124.eu1.way2cu.work/program/sample-page 

![image](https://user-images.githubusercontent.com/26923359/30015763-e060283a-915a-11e7-81ea-fad083b05f6b.png)

How page sepoes to show: 
![image](https://user-images.githubusercontent.com/26923359/30015895-5eb2e90c-915b-11e7-9e30-63d37e75f699.png)

**Comment by talovdat** [comment]
This issue was confirmed on Android and iPhone devices.

**Comment by MeanEYE** [comment]
@VladimirWebDev there's a mixed-in function in `functions.less` for sizing items so they fit in number of columns in parent space. This needs to be applied for these buttons. As for image, it's not so much of a problem as @talovdat didn't know how to assign image to the page.

**Comment by MeanEYE** [comment]
Buttons look bad because @talovdat added note with `**two stars**` right next to links. This results in them being broken due to additional content in the same paragraph with link. This is not an issue with us.
