### ISSUE TITLE
Careers page article visibility

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#120]
For times that there is no position available, the client will hide the position articles and instead will appear a message (manageable text) about the lack of available positions.

Page URL - http://yuni.co.il.82-223-16-124.eu1.way2cu.work/careers

**Comment by VladimirWebDev** [comment]
@MeanEYE  Simplest solution I find here is for me to add `only_visible` attribute and when there is no open positions they check show, previously created message article. When they have open position just switch visible articles. Hope I explain good..
