### ISSUE TITLE
New articles still don't get automatic header image

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#121]
Two links for examples.
http://yuni.co.il.82-223-16-124.eu1.way2cu.work/program/yuval
http://yuni.co.il.82-223-16-124.eu1.way2cu.work/program/news1

Screen shot from first link (program/testimonies - 1st link)
![image](https://user-images.githubusercontent.com/26923359/39966425-3561eade-56b4-11e8-8773-eee370927d3f.png)

![image](https://user-images.githubusercontent.com/26923359/39966367-4f53d6a6-56b3-11e8-81b1-1b35bd58f0f1.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev check this one as well. Am getting suspicious this is just poorly entered content.

**Comment by MeanEYE** [comment]
Long story short: _it's a content issue_. But we need a default image even if they don't assign text_id or image.

**Comment by MeanEYE** [comment]
@VladimirWebDev, news items should have a default header image and header line needs to go from edge to edge on that page. 

Yuval page on the other hand should work by specifying image with same text id. Right?

**Comment by VladimirWebDev** [comment]
That news1 page is part of program pages, so same answer for both, text_id should match. As for bad padding on article I'll check..

**Comment by VladimirWebDev** [comment]
Bad padding is because of I specified padding on article instead on `ul`. That is fixed. For images, just adequate text_id, same as text_id of article.

**Comment by MeanEYE** [comment]
It's not a solution, because second news will be `news2` and so on. 
We can't reasonably expect them to upload an image for each news item.
