### ISSUE TITLE
Translate English message to Hebrew

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#122]
I need to change the message (pointed out in the screenshot) 
to Hebrew.
Can I do it through the language file?
![image](https://user-images.githubusercontent.com/26923359/40177388-27a212c6-59e7-11e8-962e-acd0f4976b8b.png)

**Comment by VladimirWebDev** [comment]
@talovdat It can be changed from backend.

**Comment by talovdat** [comment]
Thanks.
