### ISSUE TITLE
Careers article visibility

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#125]
On career page, when making the "no position available" article not visible it will stay on the page with the other articles. 
We need to show either the "no position available" or the other articles. 
Can't show them both. 
URL : http://yuni.co.il.82-223-16-124.eu1.way2cu.work/careers

![image](https://user-images.githubusercontent.com/26923359/40883866-8f3c598e-670f-11e8-8c04-de0d846f420e.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev you tested this?

**Comment by VladimirWebDev** [comment]
Yes but bad. I only need to add `only-visible` when calling `show_list` on articles in group careers because otherwise it shows all articles and it will show also this no-open-jobs article even if it's checked no visible.

**Comment by MeanEYE** [comment]
What?
Why?

**Comment by VladimirWebDev** [comment]
I created no-open-positon article to belong to same group as other carrer articles cause I thought it should be with other articles belonging to same page. I just add `only_visible` attribute so if mentioned article is checked not visible, it will not be shown.
