### ISSUE TITLE
Links are still lacking of style

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#126]
This issue is still on.
![image](https://user-images.githubusercontent.com/26923359/41092966-d0d17262-6a52-11e8-9562-7e507ee92acf.png)

For example, location page still has some unreadable lacking style links.

**Comment by VladimirWebDev** [comment]
Last two changes are not deployed yet. That is the cause of this issue still present.

**Comment by talovdat** [comment]
@MeanEYE What is the status on the deployment?

**Comment by VladimirWebDev** [comment]
Changes deployed..
