### ISSUE TITLE
Missing page subtitle.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#18]
Text should appear on all header images inside inner pages. 
For example:
![image](https://user-images.githubusercontent.com/26923359/30324797-f695b130-97ca-11e7-9041-e6d0c939effe.png)

**Comment by MeanEYE** [comment]
This is already done. Just create `H3` at the beginning of page text and it will be moved above the image.

**Comment by talovdat** [comment]
Done, thanks.
