### ISSUE TITLE
Aligned to center links buttons

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#23]
Please Aligned to center all links buttons.
![image](https://user-images.githubusercontent.com/26923359/30371583-b792e6b0-9883-11e7-8d2f-4c1a8de6b491.png)

**Comment by MeanEYE** [comment]
Those buttons have line breaks after them, otherwise they would be in two columns. Centering them is not doable without wrapping them in some sort of container.

**Comment by MeanEYE** [comment]
@talovdat we should test this feature with quote blocks. By adding `>` before the button link you can create a quote block. Since this site won't have anything to quote, we can use this syntax for centering buttons.

After that is done on sample page, @VladimirWebDev will do the implementation.

**Comment by talovdat** [comment]
I tested the quote blocks feature and those are the results: 
![image](https://user-images.githubusercontent.com/26923359/30520577-11819a94-9bb9-11e7-9d41-2585ac15d027.png)


As you can see it's not entirely centred and made the buttons shorter which broke the text.

**Comment by MeanEYE** [comment]
What's the container size? We should also override style for buttons inside of quote block.
