### ISSUE TITLE
News bar side arrows not showing

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#25]
News bar, not manageable, meaning you can't press the arrows on the side.
![image](https://user-images.githubusercontent.com/26923359/30539953-9e112dac-9c7d-11e7-82aa-69294f2de9bf.png)

**Comment by MeanEYE** [comment]
This requires custom widget to be programmed. Not an issue as I can use one of the existing ones, but why was it designed and requested like this?

It's not really usable. First of all, news which doesn't have a date is not news. How would someone know if something is still relevant or not? Etc.

**Comment by talovdat** [comment]
It will show date inside news page, the news bar meant for news headlines, you see something interesting, you click on the news.. or just clicking on the arrows to see if there is something new that might draw your attention to the news section.

**Comment by MeanEYE** [comment]
Am not convinced this is good enough. But I'll do this.

**Comment by MeanEYE** [comment]
@VladimirWebDev this one is on pause until we resolve it with client.
