### ISSUE TITLE
Home page - make logo bigger

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#28]
Please make the logo bigger. 
![image](https://user-images.githubusercontent.com/26923359/33380473-de1a6998-d523-11e7-9a6e-ab08ed8c2185.png)

**Comment by talovdat** [comment]
Basically, we need to stretch the logo and the text to cover all the header, except the menu bar. 
If that doesn't work visually, we should leave the logo with just the upper text, and take the lower text and put it next to the bottom logo that we decreased by at least 50%.

If it sounds confusing, hope the next image will suffice:

![image](https://user-images.githubusercontent.com/26923359/33426928-3606cd38-d5cc-11e7-91ae-438b572467a2.png)


A - Stay the same
B - Cover the whole header
C - Goes to the bottom of the page
D - Remove from page completely 
E - Decrease by at least 50%

**Comment by MeanEYE** [comment]
This is just on the mobile version?

**Comment by talovdat** [comment]
No. Apply to both mobile and desktop versions.

**Comment by VladimirWebDev** [comment]
@talovdat B and C parts are one svg icon called icon-logo.svg. Are you 100% sure that should be divided..?

**Comment by talovdat** [comment]
@VladimirWebDev , If making the entire logo (both B and C) larger will look visually acceptable, then no need to divide them. 
If not, we will divide them as we make C a text, end move it to the bottom.

**Comment by VladimirWebDev** [comment]
@talovdat , @MeanEYE I'll close this issue. I've done everything needed. If solution is not satisfying reopen issue.
