### ISSUE TITLE
Mobile version - location page, scrolling not working properly 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#31]
When a lightbox is open, you can scroll the page in the background and not the lightbox itself. 

![image](https://user-images.githubusercontent.com/26923359/33437968-36b19e04-d5f2-11e7-8a5a-114adb5771e9.png)

**Comment by MeanEYE** [comment]
That is because dialog is in fixed position, so it doesn't move. This should be fixed in a different way. Content of the dialog should be scrolled while maximum dialog content size set.

**Comment by VladimirWebDev** [comment]
Fixed height of div.popup is set and added overflow-scroll. Now longer content and close button are visible after scrolling down. Need confirmation that this is correct solution.
