### ISSUE TITLE
Location page - Move 'close' button to the top

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#32]
Inside the location page move the 'close' button to the top of the lightbox. 
![image](https://user-images.githubusercontent.com/26923359/33438415-7353fe78-d5f3-11e7-9469-d863d02fa925.png)

*If it looks bad visually, make it an X sign.

**Comment by MeanEYE** [comment]
Reason?

**Comment by talovdat** [comment]
In some devices, the dialog is too big that you can't see the 'close' button. 
And Most of the closing window buttons on the web are on the top right.

**Comment by MeanEYE** [comment]
Solution I've offered on issue #31 solves this one as well. And I don't thing people will have an issue recognizing what that button does as long as it's visible.
