### ISSUE TITLE
Matching icon color inside inner pages

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#33]
Every category has it's own color as you can see on the homepage: 
![image](https://user-images.githubusercontent.com/26923359/33439278-b66f7d34-d5f5-11e7-81c2-74b99987c16e.png)

Each inner page should have his icon and icon color to match the main menu icons. 

For example, in /courses/math-enrichment the color of the icon is Yellow when it should be blue as the homepage courses icon is.
![image](https://user-images.githubusercontent.com/26923359/33439576-73307a04-d5f6-11e7-87f2-5b2fd48fc975.png)

**Comment by MeanEYE** [comment]
Additionally sizes are bigger than they should be. Icon should be inside of the squiggly frame.

**Comment by talovdat** [comment]
The issue hasn't been fixed in the desktop version. 
My fault for not mentioning it should be done in both versions, mobile, and desktop. 
Please do so.
