### ISSUE TITLE
"Our team" page 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#35]
Page has no design for it so I'll explain it all here. 

Current URL end's with  /program/program2
It should be  /staff _or_ /ourteam or something like that.

The UX work's like that: 
In the main menu, you press program and it is the fourth option from the top. 

Header image:
*Client provided, should I upload it through the backend or send it to you guys?
It should have the "program" icon as all program inner page has. 

the headline: 
אנשי הצוות (Our staff)

As for the content, it should have a gallery with hovering effect when the image is changed to the content on the tutor.
Here's a link for example: 
http://ebagcourses.cet.ac.il/%D7%94%D7%90%D7%AA%D7%92%D7%A85/
And a screenshot if the link doesn't work:
![image](https://user-images.githubusercontent.com/26923359/33526948-f872bc34-d850-11e7-86f1-062ce0383e68.png)

**Comment by MeanEYE** [comment]
These are to be saved in gallery. Each image has title and description which can be used as name and details. Template I propose to be:

```xml
<figure>
<img src="..."/>
<figcaption>
<h3>Name</h3>
... description ...
</figcaption>
</figure>

**Comment by MeanEYE** [comment]
@talovdat background image for header provided is utter garbage. We can't put that there. We need better one.
