### ISSUE TITLE
New header images - inner pages. 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#36]
Shared via Google drive, a folder called "Yuni - header images - inner pages"
Please set the images by their names.
Each image match each inner page.

To be on the safe side, inner pages are:
sign-up
articles
about us
acceptance 
faq
testimonies 

*A small reminder, each header image should have their own icon on it. 
![image](https://user-images.githubusercontent.com/26923359/33842790-3bc35a62-dea4-11e7-8b32-e6f9ce5b856c.png)

**Comment by MeanEYE** [comment]
Don't clump issues together @talovdat, there's no need to remind anyone of anything.
