### ISSUE TITLE
Contact-us page

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#38]
please add a subject selection field to the contact form.
Tell me if you need a list of the subjects.

**Comment by MeanEYE** [comment]
List od subjects?

**Comment by talovdat** [comment]
For the selection, when the user is filling the details in the contact form, he can choose a subject in regard to his submission.

**Comment by MeanEYE** [comment]
This can be added regardless of us coders just by opening backend and adding another field.
