### ISSUE TITLE
Location page - map design

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#39]
Client approved the concept @MeanEYE and Hanan talked about. 
Please design the map as agreed.

**Comment by MeanEYE** [comment]
I don't really do design and I would need someone to provide me with vector image of Israel they want to appear in selection.

**Comment by talovdat** [comment]
Michael refuses to convert the images to vector.
Didn't found a free converter online, if you know something then let me know.
If not, we will either convince Michael or hired a designer for that particular job.

**Comment by MeanEYE** [comment]
It's not paramount but it won't look as good. 
Send me the images and I'll see if I can do something.

**Comment by talovdat** [comment]
Images sent via email with subject name: Location images - YUNI project

**Comment by MeanEYE** [comment]
NONE and I repeat NONE of the images are of anything that in any shape or form resembles a map.

**Comment by talovdat** [comment]
*Vector image of the map of Israel has been provided.
