### ISSUE TITLE
Increase icons size in the submenus

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#42]
Please make the icons in the submenus bigger as they should be.

How it looks now: 
![image](https://user-images.githubusercontent.com/26923359/34167465-8613051c-e4ea-11e7-941f-00eb220e4f9d.png)

How it should look: 
![image](https://user-images.githubusercontent.com/26923359/34167520-a8e883fa-e4ea-11e7-9caf-7d1916776d72.png)

**Comment by MeanEYE** [comment]
These icons a re somewhat sensitive of a subject. It's not an issue increasing their size, but behavior you took screen shot of is different from other computers/phones. Test more and then confirm this got messed up. Also to point out not all icons are landscape so this increase won't work as good on every menu.

**Comment by talovdat** [comment]
This issue applies to - Mobile: Android, IOS,
                                   Desktop: Explorer, FireFox, Chrome
Tested on 5 different phones and three pc.

**Comment by MeanEYE** [comment]
@VladimirWebDev make sure these are constrained from both sizes. I suspect only height is set and is causing this issue since icons are not rectangular always. Each icon should have aspect ration measured from `viewBox` and applied accordingly through LESS:

```less
@size: 1.2rem;
@ratio: 1.1;
width: @size;
height: @size * @ratio;
```
