### ISSUE TITLE
Styling needed - contact-us page

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#44]
Please style the next field as the other fields on that page.
![image](https://user-images.githubusercontent.com/26923359/34256404-d6b7b318-e65d-11e7-90bc-11a506780b92.png)

**Comment by VladimirWebDev** [comment]
What about icon, there is no subject icon in sprite?
![image](https://user-images.githubusercontent.com/25882157/34257371-eccc9e92-e659-11e7-95c6-7231a3c55a6d.png)

**Comment by MeanEYE** [comment]
@talovdat needs to resolve that part. For now use the letter one.

**Comment by talovdat** [comment]
Basically, this is the icon, Will update when I'll find it in the drive.
![image](https://user-images.githubusercontent.com/26923359/34262762-f578bcbc-e675-11e7-91ac-cefe41f6ea6e.png)

**Comment by VladimirWebDev** [comment]
I have it in a sprite.

**Comment by talovdat** [comment]
Great! use it. That should do.
