### ISSUE TITLE
Header description font needs to change

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#45]
Please change the header images description font.
New font files will be provided via email.
![image](https://user-images.githubusercontent.com/26923359/34263491-682e3e1a-e678-11e7-96c7-61506201443b.png)

**Comment by VladimirWebDev** [comment]
Whole site is now setup to use Open Sans (Regular and Bold) font family. Also specific elements like `input` , `button` and `select` are properly updated to use mentioned font. This is main font from start. Does this issue still needs to be fixed so specific headings use specific font ?

**Comment by MeanEYE** [comment]
Close the issue then. Change of font is a different issue.

**Comment by talovdat** [comment]
The issue is referring only to the header description as it says in the headline of this issue. 
New font has been provided via email in a forward message under the subject: Fwd: פונטביט‎
on this date -12/21/17 

If you having trouble finding the email let me know.
