### ISSUE TITLE
Change site font

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#46]
Header text font is ARAIL while the rest of the site, some with ARIAL and some not. 
If we do have ARIAL, please make it apply to the entire site.

**Comment by MeanEYE** [comment]
We do not have Arial. That font is configured as a backup font and only works on systems which have it. Site was designed with similar font in mind and Arial used as backup. If client still insists on using Arial, then we will have to provide a link for purchase. Purchased fonts are usually per project, which means no other site of theirs can use this than for purpose of building ours.

**Comment by MeanEYE** [comment]
Just occured to me, this site is in Hebrew. Arial doesn't have Hebrew support. So it's not even an option. Font used is Open Sans Hebrew. At least I didn't see.

**Comment by talovdat** [comment]
So how come the header is in a different font from the rest of the site? 

Example: 
![image](https://user-images.githubusercontent.com/26923359/34340331-d7df64cc-e98a-11e7-8681-099881a3a99f.png)

**Comment by MeanEYE** [comment]
We are using different fonts by mistake. This will be fixed. System is picking next closest font which looks similar and on your _Windows_ system it might be Arial. First step is to make all elements use the same font. Then we can see about the type of font.
