### ISSUE TITLE
Add a 'search' option to the site 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#47]
Please add a search field to the site.

**Comment by MeanEYE** [comment]
I need to know what search needs to cover.

**Comment by talovdat** [comment]
All articles.

**Comment by MeanEYE** [comment]
Just articles?

**Comment by talovdat** [comment]
Can it apply to all site content?

**Comment by MeanEYE** [comment]
No. I have to manually add it for each group of the elements.

**Comment by talovdat** [comment]
Search needs to cover all of the articles.

**Comment by MeanEYE** [comment]
@talovdat we need information on where to place this search feature as original design doesn't include it.

**Comment by talovdat** [comment]
Top of the side menu. 

![image](https://user-images.githubusercontent.com/26923359/35390564-95b6ceb0-01e4-11e8-8bda-7a81701079ac.png)

**Comment by MeanEYE** [comment]
Seriously?

**Comment by talovdat** [comment]
Yes.

**Comment by MeanEYE** [comment]
Okay.

**Comment by MeanEYE** [comment]
Initial search mechanism is in place but I don't think it's matching articles properly. Once deployed @talovdat I need you to test it. I will most likely have to make a different approach to scoring articles.

**Comment by talovdat** [comment]
Tested. 
Algorithm has to be improved.
All search results show as the follow: 
![image](https://user-images.githubusercontent.com/26923359/35518860-64fe0a6a-051b-11e8-9976-be94c5cfd3a5.png)

**Comment by MeanEYE** [comment]
Okay, I'll switch from Jaro comparison algorithm to word count for scoring content searches. In the mean time, can you try searching for something that is contained in titles? Titles have significantly higher priority so they should produce some results.

**Comment by talovdat** [comment]
The screenshot above shows the results for a title.

**Comment by MeanEYE** [comment]
@talovdat recheck. Module wasn't enabled at the time.

**Comment by talovdat** [comment]
Working but not as accurate as it should be. 

Test #1 - I searched 'about the program' and half of the results were true and the other half didn't have 
              the phrase I searched for.

Test #2 - Searched 'location' and none of the results were correct.

Test #3 - Searched for 'math enrichment' in it gave me a list of location and among the long list, one 
               correct results.

Need screenshots?

**Comment by MeanEYE** [comment]
No. This is enough.

**Comment by talovdat** [comment]
Becuase this issue is not closed yet I'm not sure if the next issue should be a different one or it's okay to leave it as a comment. 

 - The search field is not working on the mobile version.
   Meaning it's not responding when I try to click on the field and write keywords. 
  
 *If it's a different issue then I'll delete this comment and open a new issue for that matter.

**Comment by MeanEYE** [comment]
New algorithm is ready. But needs to be ported to `v0.4` first. After that new testing will be needed.
