### ISSUE TITLE
Registration page - make email link usable

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#50]
In registration page ( registration/acceptance/acceptance-registra ) 
there is a link to the client email address, right now it leads to a 404 error page. 
Please make it usable for the user. 

![image](https://user-images.githubusercontent.com/26923359/34918910-c822a2c2-f963-11e7-8793-757163bffd6d.png)

**Comment by MeanEYE** [comment]
What should it do?

**Comment by talovdat** [comment]
Go to 'contact us' when clicking on it.
