### ISSUE TITLE
Free text adding on registration page

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#51]
On /registration/acceptance and all the other inner pages, there should be an option to add free text besides the links to the articles. 
Perhaps manageable from the backend office, couldn't figured out how though. 

![image](https://user-images.githubusercontent.com/26923359/34918969-c7de2f1a-f964-11e7-8b9e-129ff7150a8a.png)

**Comment by MeanEYE** [comment]
This was never in designs.

**Comment by talovdat** [comment]
That page never designed. 
If it's to much work let me know and I'll see what I can do.
