### ISSUE TITLE
Yellow background headline color match

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#54]
On each inner page, the yellow background headline should match the icon color for its specific group. 
For example, on http://yuni.co.il.82-223-16-124.eu1.way2cu.work/registration/acceptance 
the yellow line should be red as the 'registration' icon color is. 
![image](https://user-images.githubusercontent.com/26923359/35274751-fa5a82b2-0045-11e8-87c0-e43ce1bef1a5.png)

**Comment by MeanEYE** [comment]
What? Why is this being changed now? This was on original design which was approved.

**Comment by talovdat** [comment]
We only design one page back then. 
Unfortunately, it's a legit issue.

**Comment by VladimirWebDev** [comment]
What about pages that doesn't have color (except program, course, registration and contact). News page, Location main page and locations pages, Calendar page.. They all have main header but not associated color.. If I understand issue correctly all pages must have appropriate background color for header..

**Comment by MeanEYE** [comment]
Leave yellow.
