### ISSUE TITLE
Add a Youtube link on home page

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#58]
Please add a Youtube link on the home page. 
The link should appear either between 'location' and 'calendar' icons or centered under them. 
The icon is shared via Google Drive. 
Youtube video URL https://www.youtube.com/watch?v=9rhRsUTqL0Q&feature=youtu.be 
I think all you need is 9rhRsUTqL0Q correct? 

![image](https://user-images.githubusercontent.com/26923359/35276846-7326023c-004d-11e8-9659-298335ca677c.png)

**Comment by MeanEYE** [comment]
Desktop version has popup in dialog. Mobile version should just show thumbnail inside of YouTube link (`url`).
