### ISSUE TITLE
Style location pages.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Yuni-Site#59]
![image](https://user-images.githubusercontent.com/1911594/35286271-cd3e58ac-005f-11e8-8e5a-c38303026cec.png)
I did preliminary structure of the `view_location.xml` template. This template is used to show information about individual location. There's a `section#location` container around article. These need to be made similar in looks to other pages. Centered and properly formatted.

**Comment by VladimirWebDev** [comment]
![image](https://user-images.githubusercontent.com/25882157/35307059-3d1a7430-00a1-11e8-8013-71cdceac7997.png)
I've centered content as on other pages. Since no links present and it's just text I need feedback is this fine or something more needs to be done.

**Comment by MeanEYE** [comment]
They want images on some of them. Check with @talovdat which ones and see if that fits. Other than that it's fine.
