### ISSUE TITLE
'Employee wanted' page

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#62]
We need to create an 'Employee wanted' page. 
Heres an example of what Hanan and the client agreed on http://tgs-systems.com/careers 

Header, content and if possible then his own submission form.

**Comment by MeanEYE** [comment]
Which header, which content, which form fields?

**Comment by talovdat** [comment]
Hiring page Will be as follow (if possible)
general text
then a list of position wich each position will open a new page with a short description and a form.
the form can either be on the page or will show as a popup after clicking a "apply for this position" button. 
Form will have a hidden field with the position to be sent.
*can we add an option where the user can attach his CV to the submission form?  

Heres a screenshot from that site we gave the client as an example.
![image](https://user-images.githubusercontent.com/26923359/35510647-a587e156-0501-11e8-9865-5e03153867b8.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev you can do structure for this and perhaps form as well. There should be `position` field in that form which is set to `hidden` type. We will configure this field through page when the time comes. 

We need to create article group called `careers`. Any articles in them will be used as individual position. Article's `text_id` is to be used in URL forming.

Structure will have additional entries:
```json
"/careers": "careers.xml",
"/careers/{s:career}": "career_view.xml"
```
System will then use `$_REQUEST['career']` to show the correct article with that `text_id`.

**Comment by MeanEYE** [comment]
I am not sure we should make the form pop-up. Since we are doing mobile first, content of article should be displayed first, followed by form itself.

**Comment by VladimirWebDev** [comment]
Ok, but looking from main page, where should it be available from.. is it part of program sub pages or somewhere else..?

**Comment by MeanEYE** [comment]
That I do not know. I think client probably has an idea where it should be linked from.

**Comment by talovdat** [comment]
I'll provide you with an answer for this one.

**Comment by VladimirWebDev** [comment]
Few questions about main career page:
- [ ] Should it have header image?
- [ ] Should it have icon on top of header image, if yes needs to be provided..
    (Like all pages) 
![image](https://user-images.githubusercontent.com/25882157/35519483-ab4ccb16-0514-11e8-876b-af4343d70381.png)

- [ ]  text for tab title (e.g. like on picture for calendar page)
       
![image](https://user-images.githubusercontent.com/25882157/35519582-f20f6b6c-0514-11e8-9448-05dca9e67943.png)
- [ ] Text for career main page main title.
- [ ] This is picture from sample site -> job opening 
       
![image](https://user-images.githubusercontent.com/25882157/35519771-79096ad2-0515-11e8-8dcd-93bba10b0528.png)
   Should it have date when job position is opened.?

**Comment by MeanEYE** [comment]
Doesn't have or need due date, they can just hide the article. In my opinion date of posting shouldn't be there either as it can give the wrong impression to people reading the page. If the ad is months old, people might doubt its validity, when in fact client might be still looking for more employees.

Everything else should be provided. Yes we will have header image, icon is perhaps optional but should be there considering it's on every other page, page title fragment needs to be also provided, etc.

**Comment by talovdat** [comment]
- Header image should be the same as 'about the program page' 
![image](https://user-images.githubusercontent.com/26923359/35573414-bbefd83e-05df-11e8-83f5-eb55f80f520b.png)

- I have the icon, I need to know if you guys need the code or SVG cause that's what https://icomoon.io/app/#/select/image offers me. 

- text for tab title (e.g. like on picture for calendar page) - דרושים 

- Icon will be placed on the home page in the following order: 

![image](https://user-images.githubusercontent.com/26923359/35615450-d3f896dc-067a-11e8-8509-bc5b9a93c881.png)

A - location 
B - career 
C - youtube
D - calendar 
*If it's not possible or to much let me know and we will make it different and simpler. 

The page will be called דרושים

**Comment by MeanEYE** [comment]
Ordering is a waste of space and not a good idea. To achieve it we would have to place them in separate containers and therefore make it less friendly to search engines.

As for original question: We need SVG.

**Comment by VladimirWebDev** [comment]
For test purpose I put link like this.. Icon is missing however, but you get the idea @talovdat 
![image](https://user-images.githubusercontent.com/25882157/35618240-a85f0754-067a-11e8-875c-61a95ad1d2fd.png)
I will also need text for that link..

**Comment by talovdat** [comment]
Text for that link is דרושים
Icon shared on google drive under the name 'icomoon_1_icons.zip'
*the icon is lack of style like the other icons, is that an issue? if so, I'll have it design.

**Comment by talovdat** [comment]
Correct, as I mentioned in my last comment. 
If possible make it like the other, if not then I'll design it.

**Comment by VladimirWebDev** [comment]
Problem is that all other images are PNG so I can not get that ram.. If possible this SVG icon should be corrected with ram..

**Comment by MeanEYE** [comment]
What the hell is ram? And I agree. Send me the icon, I can do it easily for you.

**Comment by VladimirWebDev** [comment]
Frame... Mixing languages.. Sorry
