### ISSUE TITLE
News bar functionality

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#63]
No matter what news headline I click on, it takes me to the last article on the news page. 
Each article headline on the news bar should lead to the same on the news page. 

Click on this one:
![image](https://user-images.githubusercontent.com/26923359/35362650-dae86e74-016e-11e8-8820-90c941cff7e0.png)

Open the page already scrolled down to the last article(by default).
![image](https://user-images.githubusercontent.com/26923359/35362694-0f0c8bd6-016f-11e8-9529-1e7436d77c37.png)

**Comment by talovdat** [comment]
Apply to both mobile and desktop.

**Comment by MeanEYE** [comment]
Small arrow appears on selected news. This is because we have news page, and not individual pages for each news, since that would be stupid for such small amount of content. So it's not the same behavior. Just similar. I do agree this page needs to be improved.

**Comment by talovdat** [comment]
They tend to put there a lot of news articles if that changes anything.

**Comment by MeanEYE** [comment]
They need to state things as such since we are the ones who need to make that usable. Vladimir already did some optimization on that part so once we upload changes we'll see if those suffice. If not we'll further improve.

**Comment by VladimirWebDev** [comment]
Issue with news links leading to same news fixed. Improved style on news articles. If solution is not satisfying please reopen issue..
