### ISSUE TITLE
Adding table chart to the articles

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#64]
We need to make it possible to add and manage a table chart inside the articles.

**Comment by MeanEYE** [comment]
By table chart you mean what?

**Comment by talovdat** [comment]
For example, here you have a chart of which program goes to which location.
![image](https://user-images.githubusercontent.com/26923359/35395150-3821d174-01f2-11e8-9fe9-8eceda080c24.png)

**Comment by MeanEYE** [comment]
That is a **table** not a chart. User can already add these.
