### ISSUE TITLE
Spelling mistake on homepage header

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#65]
We need to add one letter to the homepage header.
![image](https://user-images.githubusercontent.com/26923359/35363007-99af9642-0170-11e8-954a-cf6046fdd39d.png)

**Comment by MeanEYE** [comment]
That is their logo they sent to us. An image as far as I know. I'll have @VladimirWebDev check to make sure, but as far as I know it's a logo image.

**Comment by talovdat** [comment]
Yes, there is a missing letter.

**Comment by VladimirWebDev** [comment]
@MeanEYE how to fix this..?

**Comment by MeanEYE** [comment]
@VladimirWebDev is it live text or paths?

**Comment by VladimirWebDev** [comment]
Paths, that is problem..

**Comment by MeanEYE** [comment]
@talovdat is that letter available somewhere in the text? If so we might be able to copy it, if not whoever made the logo has to correct the mistake as we don't have those fonts.

**Comment by talovdat** [comment]
Yes, it is. The letter is ו 
pointed out in the next screenshot:
![image](https://user-images.githubusercontent.com/26923359/35394900-99822a46-01f1-11e8-9944-842c97a6deac.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev if you can fix this. Also @talovdat make sure that footer one doesn't have the same mistake if they contain the same words.

**Comment by talovdat** [comment]
Footer is fine.
