### ISSUE TITLE
Upload 'PDF download links' on articles

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#67]
Make an option to upload a PDF as a link when clicked on it download automatically the PDF.

**Comment by MeanEYE** [comment]
Need the design description and location.

**Comment by talovdat** [comment]
Can we make it look like a link? 
Location will be manageable in any article if possible.

**Comment by MeanEYE** [comment]
For that all we need to do is enable downloads module and then a button on article toolbar will appear which will contain download link.

**Comment by VladimirWebDev** [comment]
@talovdat Downloads module is enabled and initialized. When adding new articles or modifying existent _add download link_ option will be available in article toolbar as Mladen stated.. PDF file should be uploaded first then adding link is simple.
