### ISSUE TITLE
Shadow effect headline

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#68]
![image](https://user-images.githubusercontent.com/26923359/35396014-864e224c-01f4-11e8-8156-7c305f7c8f51.png)

A - Shadow effect will be removed(the text on it also)
B - Font of the headline changes to the special font she bought. 

_Font color_
Yellow line with black font
Blue line with white font
Red line with white font
White line(contact-us) with black font

(The colors mentioned above are the main icons and groups color)

**Comment by MeanEYE** [comment]
You remember the talk about accessibility? Well this is it. This is them messing it up.

**Comment by talovdat** [comment]
She well aware of that.

**Comment by MeanEYE** [comment]
Then am accepting this issue.
