### ISSUE TITLE
Images inside articles looks bad

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#7]
All the images inside articles are missing icons and text.
Proper image(took from design):
![image](https://user-images.githubusercontent.com/26923359/29559492-eca81940-8737-11e7-9cc9-98ed827e4211.png)

Current image example from site: 
![image](https://user-images.githubusercontent.com/26923359/29559570-20f9f466-8738-11e7-907b-83d3f71868ca.png)

**Comment by MeanEYE** [comment]
Mobile or desktop version. Design didn't originally have the icon as far as I remember.

**Comment by talovdat** [comment]
The design is the same thing as the structure.
There you can see the way it should be. 
![image](https://user-images.githubusercontent.com/26923359/29567850-18a252ee-8757-11e7-8e9c-b649074a4fd4.png)
icon and text on image, both mobile and desktop version.
