### ISSUE TITLE
Side menu doesn't close

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#70]
The side menu doesn't close after clicking on it for the second time. 
First click - open
Second click - nothing happens. 

![image](https://user-images.githubusercontent.com/26923359/35520217-1add25fc-051f-11e8-98bd-5491159bf623.png)

**Comment by MeanEYE** [comment]
This can be solved with CSS and use of a single checkbox. And I would prefer it to be solved that way instead of resorting to JS. If you need further instructions let me know.

**Comment by VladimirWebDev** [comment]
@MeanEYE  Need confirmation that fix I did is correct. Than I 'll close issue..

**Comment by MeanEYE** [comment]
You can close.
