### ISSUE TITLE
Side menu not working - Moblie

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#72]
The side menu is not working on the mobile version. 
Open when clicking on but not functioning from that point.

**Comment by MeanEYE** [comment]
@VladimirWebDev I need this confirmed.

**Comment by VladimirWebDev** [comment]
Hmm. Issue is legit. Menu is not working, instead of menu items, links behind menu are activated..
![image](https://user-images.githubusercontent.com/25882157/36156244-bd13d984-10d6-11e8-9062-e7cc7cd2e666.png)
If clicked on first item in programs, actually news link behind is activated..

**Comment by VladimirWebDev** [comment]
I made a mistake with solution for clicking on menu. 
When defined `input:checked ~ nav` I haven't redefined `pointer-events` from `none` to `auto`.
This is now solved and last commet on issue: https://github.com/Way2CU/Yuni-Site/issues/47,  is also connected with that.

**Comment by MeanEYE** [comment]
OKay!
