### ISSUE TITLE
our-team page - image matching size | mobile

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#73]
On the mobile version, the size of the tutor is not equal.
Please make it one size to all of the images on that page. 

![image](https://user-images.githubusercontent.com/26923359/36099985-48da8000-100d-11e8-8c55-260f460a11a2.png)

URL: http://yuni.co.il.82-223-16-124.eu1.way2cu.work/program/our-team

**Comment by MeanEYE** [comment]
This should be solved by coming up with some aspect ratio of the container wrapping the image and then enforcing that aspect ration. Any overflow should be set to `hidden` on that container.

**Comment by MeanEYE** [comment]
@talovdat this issue will look weird until client realizes they need similar or same size images.
