### ISSUE TITLE
Location page - going back to old version

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#75]
We need to undo the map and go back to the old version.
Plus the page is broke: 
(let me know if you need a different issue for that)
![image](https://user-images.githubusercontent.com/26923359/36975530-0b6b8fd0-2083-11e8-9a92-d8a0aabe7db6.png)
 

This issue applies to both mobile and desktop.

**Comment by MeanEYE** [comment]
Empty space is not a bug, it's just there because content is lacking. As for map it should be removed, as well as accompanying script, and replaced with a list of locations which lead to different pages.

**Comment by VladimirWebDev** [comment]
@MeanEYE first version of locations page, on mobile version, have location articles displayed in popup not as whole different page.
![image](https://user-images.githubusercontent.com/25882157/37028687-3b79f70e-2135-11e8-9c2f-8af558d6bd31.png)
How to do that..? As popup or separate page.?

**Comment by MeanEYE** [comment]
We are not doing the popup thing. 
Check if database still has categories for locations.
