### ISSUE TITLE
Our team page - desktop

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#76]
![image](https://user-images.githubusercontent.com/26923359/36975698-93ac7cce-2083-11e8-8cc6-2655959604e8.png)

the images do not fit in their window.

**Comment by VladimirWebDev** [comment]
When image is properly scaled, I have issue cause of white text.
![image](https://user-images.githubusercontent.com/25882157/36987650-2a04677c-209d-11e8-8f32-bccfefbb85b0.png)
Sometimes it is hard to read if image in the background is white..
I can solve this with some `background-color` 
![image](https://user-images.githubusercontent.com/25882157/36987750-676195a4-209d-11e8-8feb-683f030db362.png)

**Comment by MeanEYE** [comment]
Why didn't we solve image size issue yet?
Also you should have darker colors than yellow, check the LESS files.

**Comment by VladimirWebDev** [comment]
"Darker colors", instead of yellow, like on picture..?  I used yellow since it's program page.
