### ISSUE TITLE
Homepage - mobile

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#77]
The homepage in the mobile version got the same design as the new desktop version. 
Homepage on desktop and homepage on mobile are two different things. 
![image](https://user-images.githubusercontent.com/26923359/36975880-3c257842-2084-11e8-811e-21a0fc0dabb5.png)
 

This is how it looks on the mobile version.

**Comment by MeanEYE** [comment]
Only difference is inclusion of YouTube video. Everything else is fine.
