### ISSUE TITLE
Header size - desktop

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#78]
The header size should be much smaller according to the design. 

How it should be:
![image](https://user-images.githubusercontent.com/26923359/36976081-ef9c1fb6-2084-11e8-9fb8-65ef6a9ccfde.png)

How it is right now: 
![image](https://user-images.githubusercontent.com/26923359/36976101-086e651c-2085-11e8-897d-403eefbaa3eb.png)

**Comment by MeanEYE** [comment]
We can enforce a certain size, but then client has to stick to that size, which they clearly are not capable of doing.
