### ISSUE TITLE
Make icon in main menu smaller

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#8]
Icons in the main menu are too big. 
Make them like the design - 
![image](https://user-images.githubusercontent.com/26923359/29560827-eb9052ee-873b-11e7-806a-af7ac45b9146.png)

Currently looking like that - 
![image](https://user-images.githubusercontent.com/26923359/29560897-2f327590-873c-11e7-8ff5-b4f1d2b925c9.png)

**Comment by MeanEYE** [comment]
![image](https://user-images.githubusercontent.com/1911594/29566794-52f68426-874b-11e7-9e11-115df009149a.png)
Exactly how they are right now. Test with other computer/browser.
