### ISSUE TITLE
Avoid missing icon and background images

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#80]
Do not allow cases where there's either icon or background image missing.

**Comment by VladimirWebDev** [comment]
I need more specific explanation for this, or example. As requested every page on site have option to add and specify header image, also every page have matching icon. Missing header images can come from not defining image for page or bad defining. It is programmed that every article's text_id match text_id of image inside proper gallery group (like courses, programs, etc).
So if article with `text_id` about-us is created, and it belongs to group `programs`, than image should be uploaded to group `programs` with `text_id` about-us.

**Comment by MeanEYE** [comment]
That's exactly where the issue is. 
If there's nothing specified default image should be used.

**Comment by talovdat** [comment]
There are a few pages that are missing background image and icon, for example - http://yuni.co.il.82-223-16-124.eu1.way2cu.work/news#no4

![image](https://user-images.githubusercontent.com/26923359/38175600-abe08528-35e7-11e8-9362-65305d0f5d09.png)

**Comment by VladimirWebDev** [comment]
When clicking on news feed it goes to page where are all news displayed and specific - clicked one is shown. It is not problem to add image and icon. I'll need image and icon..

**Comment by talovdat** [comment]
Same image and icon as in 'about the program'
