### ISSUE TITLE
Menu in popup exceed page height.

### ISSUE THREAD

**Issue by VladimirWebDev** [Way2CU/Yuni-Site#85]
![image](https://user-images.githubusercontent.com/25882157/37294259-b9f7822e-2615-11e8-8942-0df79b521ff5.png)
When clicking on e.g program link, menu in popup exceed page height on my screen. It is positioned `fixed`,`20vw`, `top`, and with current number of program pages menu goes off the screen at the end.

**Comment by MeanEYE** [comment]
It should be positioned in a different way. We can use `top: 50%` and then `transform: translatey(-50%)`.
