### ISSUE TITLE
Width of navigation of main menu.

### ISSUE THREAD

**Issue by VladimirWebDev** [Way2CU/Yuni-Site#86]
![image](https://user-images.githubusercontent.com/25882157/37295173-c77ed058-2617-11e8-941f-86ff5312cc14.png)
Just proposition, to increase width of `nav` so we do not have words breaking in menu. Desktop version.

**Comment by MeanEYE** [comment]
One of the things we wanted to do. Yes, definitely increase width. Search button needs to be next to input field. Also we'll create a JS that will hide and show submenus.
