### ISSUE TITLE
Make bottom text on home page same size

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#91]
![image](https://user-images.githubusercontent.com/26923359/37343801-52407fc0-26d1-11e8-9663-131f23a3ede6.png)
 We need to make A the same size as B

**Comment by VladimirWebDev** [comment]
![image](https://user-images.githubusercontent.com/25882157/37365059-9f785eae-26fc-11e8-822f-2c2a6e52eb60.png)
Smaller or bigger than this example.

**Comment by MeanEYE** [comment]
Smaller. He's referring to the biggest text inside of logo.
