### ISSUE TITLE
Table - text goes out of line

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#92]
Things to fix:

- [x] Forced width of the table;
- [ ] Email addresses as links.

![image](https://user-images.githubusercontent.com/26923359/37344237-85868be4-26d2-11e8-9604-faf844f902e0.png)

The email addresses go out of the table line.

**Comment by MeanEYE** [comment]
First of all we need to let the cells be of different width. Once that is done, content should be changed for emails to be links. Such thing can be achieve with `(text)[mailto:email]` format.

**Comment by VladimirWebDev** [comment]
Initially I've set `table-layout: fixed` which led to this issue. I've change it and now content dictate width of cells.
![image](https://user-images.githubusercontent.com/25882157/37405107-192c4fa2-2794-11e8-93fa-18758dee75ad.png)
I'll leave open issue cause links should be created.

**Comment by MeanEYE** [comment]
Since @talovdat is not going to be available for a while I am closing this issue. It's something that can be subsequently improved by us or client.
