### ISSUE TITLE
One size for "press here" links buttons

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#93]
We need to set one default size for all "press here" links button on the site.
![image](https://user-images.githubusercontent.com/26923359/37344688-bd46d934-26d3-11e8-928b-8f20f7a0711b.png)

The example took from program/article

**Comment by MeanEYE** [comment]
First we need to figure out why they are all in different size.

**Comment by VladimirWebDev** [comment]
I've used mixin `elements-in-row()` on one page but defined it on default level for all articles and those few buttons have width set. Other buttons are part of `li` tag and have a different style. I'll check all pages and fix this..

**Comment by MeanEYE** [comment]
Okay.
