### ISSUE TITLE
Check spacing between the lines

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#94]
Please check the spacing between the lines. 

For example: 
![image](https://user-images.githubusercontent.com/26923359/37345122-de12f6ce-26d4-11e8-8d00-cd7c00c84410.png)

**Comment by VladimirWebDev** [comment]
`line-height` is set to 1. As on all paragraphs. @talovdat They want bigger spacing between lines in paragraphs..?

**Comment by MeanEYE** [comment]
Where is the spacing set? Usually it's more like 1.1 or 1.2. So I am probably resetting that by accident. This is a bug and not a thing they just want.
