### ISSUE TITLE
Delay hiding of the menu

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#95]
We need to delay the hiding of the drop-down menu. 
![image](https://user-images.githubusercontent.com/26923359/37345353-67c3fe36-26d5-11e8-834f-9c9a00d78731.png)

**Comment by VladimirWebDev** [comment]
@MeanEYE is simple use of `transition` enough here..?

**Comment by MeanEYE** [comment]
Yes, `transition-delay` is enough. However it should only apply to hiding the menu, not showing as well.
