### ISSUE TITLE
Make all articles look uniform

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#96]
We need to make all the articles look uniform.

**Comment by MeanEYE** [comment]
This will need a little bit more clarification. I forgot what this was about since we last talked.

**Comment by talovdat** [comment]
Every new article they add looks different.
For example, program/sciencenight is a new article which they added look like that:  
![image](https://user-images.githubusercontent.com/26923359/37408992-edfde842-27a5-11e8-94ad-02fd996513b3.png)


looks a lot different than this article taken from about the program page 
![image](https://user-images.githubusercontent.com/26923359/37408920-c7d736a0-27a5-11e8-9cde-05736a76b9cc.png)

**Comment by VladimirWebDev** [comment]
Design they provide shows that if there is image text and button, as a meaningful block they should be displayed as on second image.
http://yuni.co.il.82-223-16-124.eu1.way2cu.work/program/sciencenight  Science night page have two banners with events that happened and I centered them from reason they are commercial banners. Probably I made mistake, so if it should be like on second image I'll fix that.

**Comment by MeanEYE** [comment]
We should make it so if image is `:only-child` inside of paragraph, it should be centered. Otherwise floated.

**Comment by VladimirWebDev** [comment]
Problem is that image is always only child since like on image two, text is one `<p>`, button is second `<p>` and image is in third `<p>`. For that example page I defined rules for specific paragraph e.g `p:nth-of-type(6)` and so on. Content on admin is a disaster.. I've fix it a bit, problem is language and not to brake something.

**Comment by MeanEYE** [comment]
Image is not supposed to always be only child in content. The only time that situation happens is when image is placed with empty line _before_ and _after_, as empty lines denote paragraph boundaries.
