### ISSUE TITLE
Improve behavior of the lists

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#97]
Right now the lists on the site align to the right and not matching the page. 
![image](https://user-images.githubusercontent.com/26923359/37346727-c622088a-26d8-11e8-98ef-2914c979ad29.png)

**Comment by MeanEYE** [comment]
Since this site doesn't have container for content, each element is positioned with padding. However this is a bug since I forgot to do it on lists. Both `ul` and `ol` should be properly fixed.
